// <auto-generated />
using System;
using DVLD.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DVLD.Infrastructure.Migrations
{
    [DbContext(typeof(DVLDDbContext))]
    [Migration("20260417213922_FixUserConstraints")]
    partial class FixUserConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DVLD.Domain.Entities.ApplicationType", b =>
                {
                    b.Property<int>("ApplicationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationTypeID"));

                    b.Property<decimal>("ApplicationFees")
                        .HasColumnType("smallmoney");

                    b.Property<string>("ApplicationTypeTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ApplicationTypeID");

                    b.ToTable("ApplicationTypes", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.Applications", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<int>("ApplicantPersonID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("ApplicationStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("ApplicationTypeID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidFees")
                        .HasColumnType("smallmoney");

                    b.HasKey("ApplicationID");

                    b.HasIndex("ApplicantPersonID");

                    b.HasIndex("ApplicationTypeID");

                    b.HasIndex("CreatedByUserID");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.DetainedLicense", b =>
                {
                    b.Property<int>("DetainID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetainID"));

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetainDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FineFees")
                        .HasColumnType("smallmoney");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("bit");

                    b.Property<int>("LicenseID")
                        .HasColumnType("int");

                    b.Property<int?>("ReleaseApplicationID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReleasedByUserID")
                        .HasColumnType("int");

                    b.HasKey("DetainID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("LicenseID");

                    b.HasIndex("ReleaseApplicationID");

                    b.HasIndex("ReleasedByUserID");

                    b.ToTable("DetainedLicenses", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverID"));

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("DriverID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("PersonID");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.InternationalLicense", b =>
                {
                    b.Property<int>("InternationalLicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternationalLicenseID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("smalldatetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("IssuedUsingLocalLicenseID")
                        .HasColumnType("int");

                    b.HasKey("InternationalLicenseID");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("DriverID");

                    b.HasIndex("IssuedUsingLocalLicenseID");

                    b.ToTable("InternationalLicenses", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.License", b =>
                {
                    b.Property<int>("LicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime");

                    b.Property<byte>("IssueReason")
                        .HasColumnType("tinyint");

                    b.Property<int>("LicenseClass")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PaidFees")
                        .HasColumnType("smallmoney");

                    b.HasKey("LicenseID");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("DriverID");

                    b.HasIndex("LicenseClass");

                    b.ToTable("Licenses", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.LicenseClass", b =>
                {
                    b.Property<int>("LicenseClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseClassID"));

                    b.Property<string>("ClassDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ClassFees")
                        .HasColumnType("smallmoney");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("DefaultValidityLength")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MinimumAllowedAge")
                        .HasColumnType("tinyint");

                    b.HasKey("LicenseClassID");

                    b.ToTable("LicenseClasses", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.LocalDrivingLicenseApplication", b =>
                {
                    b.Property<int>("LocalDrivingLicenseApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalDrivingLicenseApplicationID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("LicenseClassID")
                        .HasColumnType("int");

                    b.HasKey("LocalDrivingLicenseApplicationID");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("LicenseClassID");

                    b.ToTable("LocalDrivingLicenseApplications", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Gendor")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NationalNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NationalityCountryID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NationalNo")
                        .IsUnique();

                    b.HasIndex("NationalityCountryID");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.Test", b =>
                {
                    b.Property<int>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestID"));

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TestAppointmentID")
                        .HasColumnType("int");

                    b.Property<bool>("TestResult")
                        .HasColumnType("bit");

                    b.HasKey("TestID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("TestAppointmentID");

                    b.ToTable("Tests", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.TestAppointment", b =>
                {
                    b.Property<int>("TestAppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestAppointmentID"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<int>("LocalDrivingLicenseApplicationID")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidFees")
                        .HasColumnType("smallmoney");

                    b.Property<int?>("RetakeTestApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("TestTypeID")
                        .HasColumnType("int");

                    b.HasKey("TestAppointmentID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("LocalDrivingLicenseApplicationID");

                    b.HasIndex("RetakeTestApplicationID");

                    b.HasIndex("TestTypeID");

                    b.ToTable("TestAppointments", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.TestType", b =>
                {
                    b.Property<int>("TestTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestTypeID"));

                    b.Property<string>("TestTypeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TestTypeFees")
                        .HasColumnType("smallmoney");

                    b.Property<string>("TestTypeTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TestTypeID");

                    b.ToTable("TestTypes", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.Applications", b =>
                {
                    b.HasOne("DVLD.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("ApplicantPersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.ApplicationType", null)
                        .WithMany()
                        .HasForeignKey("ApplicationTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Domain.Entities.DetainedLicense", b =>
                {
                    b.HasOne("DVLD.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.License", null)
                        .WithMany()
                        .HasForeignKey("LicenseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.Applications", null)
                        .WithMany()
                        .HasForeignKey("ReleaseApplicationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReleasedByUserID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DVLD.Domain.Entities.Driver", b =>
                {
                    b.HasOne("DVLD.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Domain.Entities.InternationalLicense", b =>
                {
                    b.HasOne("DVLD.Domain.Entities.Applications", null)
                        .WithMany()
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.License", null)
                        .WithMany()
                        .HasForeignKey("IssuedUsingLocalLicenseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Domain.Entities.License", b =>
                {
                    b.HasOne("DVLD.Domain.Entities.Applications", null)
                        .WithMany()
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.LicenseClass", null)
                        .WithMany()
                        .HasForeignKey("LicenseClass")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Domain.Entities.LocalDrivingLicenseApplication", b =>
                {
                    b.HasOne("DVLD.Domain.Entities.Applications", null)
                        .WithMany()
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.LicenseClass", null)
                        .WithMany()
                        .HasForeignKey("LicenseClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Domain.Entities.Person", b =>
                {
                    b.HasOne("DVLD.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("NationalityCountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Domain.Entities.Test", b =>
                {
                    b.HasOne("DVLD.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.TestAppointment", null)
                        .WithMany()
                        .HasForeignKey("TestAppointmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Domain.Entities.TestAppointment", b =>
                {
                    b.HasOne("DVLD.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.LocalDrivingLicenseApplication", null)
                        .WithMany()
                        .HasForeignKey("LocalDrivingLicenseApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Domain.Entities.Applications", null)
                        .WithMany()
                        .HasForeignKey("RetakeTestApplicationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD.Domain.Entities.TestType", null)
                        .WithMany()
                        .HasForeignKey("TestTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Domain.Entities.User", b =>
                {
                    b.HasOne("DVLD.Domain.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("DVLD.Domain.Entities.User", "PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
